version: "3.8"

services:
  lib:
    tty: yes
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    command: /bin/sh
    image: gsh:dev
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./babel-config.json:/usr/src/app/babel-config.json
