version: '3.9'

services:
  lib:
    build:
      context: .
      dockerfile: ./prod.Dockerfile
      args:
        GITHUB_PERSONAL_TOKEN: $GITHUB_PERSONAL_TOKEN
    tty: yes    
    image: gatsby-source-hashnode:prod

