version: '3.9'

services:
  lib:
    image: gatsby-source-hashnode:prod
    build:
      context: .
      dockerfile: ./prod.Dockerfile
      args:
        GITHUB_PERSONAL_TOKEN: $GITHUB_PERSONAL_TOKEN 
        GIT_USER_NAME: $GIT_USER_NAME   
        GIT_USER_EMAIL: $GIT_USER_EMAIL   
    tty: yes    
    environment:
      NPM_TOKEN: $NPM_TOKEN

