version: '3.8'

services:
  base:
    image: gsh:base
    build:
      context: ./      
      dockerfile: dev.Dockerfile
  sample-site:
    image: gsh:base
    ports:
      - "8000:8000"
    environment:
      HASHNODE_USERNAME: $HASHNODE_USERNAME
    working_dir: /usr/src/app/packages/sample-site
    command: yarn develop
    volumes:
      - ./packages/sample-site/src:/usr/src/app/packages/sample-site/src
      - ./packages/sample-site/package.json:/usr/src/app/packages/sample-site/package.json
      - ./packages/sample-site/yarn.lock:/usr/src/app/packages/sample-site/yarn.lock
  # lib:
  #   tty: yes    
  #   image: gatsby-source-hashnode:dev
  #   build:
  #     context: .
  #     dockerfile: ./dev.Dockerfile
  #   environment:
  #     NODE_ENV: development
  #   volumes:
  #     - ./src:/usr/src/app/src
  #     - ./package.json:/usr/src/app/package.json
  #     - ./yarn.lock:/usr/src/app/yarn.lock

